"""Add node_type to graph_nodes table

Revision ID: 0351ce1a2ad9
Revises: 97363dea3d64
Create Date: 2025-04-12 12:53:07.206647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0351ce1a2ad9'
down_revision: Union[str, None] = '97363dea3d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graph_nodes', sa.Column('node_type', sa.String(), nullable=False))
    op.create_index(op.f('ix_graph_nodes_node_type'), 'graph_nodes', ['node_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_nodes_node_type'), table_name='graph_nodes')
    op.drop_column('graph_nodes', 'node_type')
    # ### end Alembic commands ###
