"""Add graph_node_id FK to notes and files

Revision ID: 33bfd45fbe58
Revises: 0351ce1a2ad9
Create Date: 2025-04-12 13:11:12.812730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33bfd45fbe58'
down_revision: Union[str, None] = '0351ce1a2ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('graph_node_id', sa.Integer(), nullable=True))
    op.alter_column('files', 'size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_index(op.f('ix_files_graph_node_id'), 'files', ['graph_node_id'], unique=False)
    op.create_index(op.f('ix_files_storage_path'), 'files', ['storage_path'], unique=True)
    op.create_foreign_key(None, 'files', 'graph_nodes', ['graph_node_id'], ['id'])
    op.add_column('notes', sa.Column('graph_node_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notes_graph_node_id'), 'notes', ['graph_node_id'], unique=False)
    op.create_foreign_key(None, 'notes', 'graph_nodes', ['graph_node_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_graph_node_id'), table_name='notes')
    op.drop_column('notes', 'graph_node_id')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_index(op.f('ix_files_storage_path'), table_name='files')
    op.drop_index(op.f('ix_files_graph_node_id'), table_name='files')
    op.alter_column('files', 'size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('files', 'graph_node_id')
    # ### end Alembic commands ###
