"""Make note content non-nullable

Revision ID: 684cdeea88f4
Revises: ce1f57c70398
Create Date: 2025-04-12 15:58:39.885356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684cdeea88f4'
down_revision: Union[str, None] = 'ce1f57c70398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
