"""Increase user_summary length in notes table to 300

Revision ID: 7b2e13c40036
Revises: 89a63378933c
Create Date: 2025-04-16 21:50:16.637561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2e13c40036'
down_revision: Union[str, None] = '89a63378933c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_summary', sa.String(length=300), nullable=True))
    op.drop_index('ix_notes_graph_node_id', table_name='notes')
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_index('ix_notes_user_id_updated_at', 'notes', ['user_id', 'updated_at'], unique=False)
    op.create_unique_constraint(None, 'notes', ['graph_node_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='unique')
    op.drop_index('ix_notes_user_id_updated_at', table_name='notes')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.create_index('ix_notes_graph_node_id', 'notes', ['graph_node_id'], unique=False)
    op.drop_column('notes', 'user_summary')
    # ### end Alembic commands ###
