"""Add label column to graph_edges table

Revision ID: 89a63378933c
Revises: 684cdeea88f4
Create Date: 2025-04-15 19:16:57.332816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a63378933c'
down_revision: Union[str, None] = '684cdeea88f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graph_edges', sa.Column('label', sa.String(), nullable=True))
    op.create_index(op.f('ix_graph_edges_label'), 'graph_edges', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_edges_label'), table_name='graph_edges')
    op.drop_column('graph_edges', 'label')
    # ### end Alembic commands ###
