"""Add position columns to notes table

Revision ID: c416d207b7c7
Revises: 2fec27e9c0f5
Create Date: 2025-04-12 11:09:04.113787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c416d207b7c7'
down_revision: Union[str, None] = '2fec27e9c0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('position_x', sa.Float(), nullable=True))
    op.add_column('notes', sa.Column('position_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'position_y')
    op.drop_column('notes', 'position_x')
    # ### end Alembic commands ###
